return {
	uiVolume = 0.2,
	startSound = "Herta.wav",
	scoreSystem = "soundsphere",
	judge = "",
	health = "",
	staticCursor = true,
	chartLengthBeforeArtist = false,
	panelBlur = 4,
	chromatic_aberration = 0.008,
	distortion = 0.004,
	spectrum = "inverted",
	backgroundEffects = true,
	showSpectrum = true,
	colorTheme = "Claude",
	showOnlineCount = true,
	vimMotions = false,
	scrollAcceleration = true,
	scrollHoldSpeed = 0.07,
	scrollClickExtraTime = 0.05,
	language = "English",
	alwaysShowOriginalMode = false,
	transitionAnimation = "circle",
	osuResultScreen = false,
	osuResultSkin = "None",
	hpGraph = true,
	showPP = true,
}
