return {
    uiVolume = 0.2,
    startSound = "Herta.wav",
    scoreSystem = "soundsphere",
    judge = "",
    health = "",
    staticCursor = true,
    chartLengthBeforeArtist = false,
    panelBlur = 4,
    chromatic_aberration = 0.003,
    distortion = 0.003,
    spectrum = "inverted",
    backgroundEffects = true,
    showSpectrum = true,
    colorTheme = "Default",
    showOnlineCount = true,
    vimMotions = false,
    scrollAcceleration = false,
    scrollHoldSpeed = 0.07,
    scrollClickExtraTime = 0.05
}
