return {
	quit = "escape",
	increaseVolume = { mod = { "ctrl", "'" } },
	decreaseVolume = { mod = { "ctrl", ";" } },
	play = "return",
	showMods = "f1",
	random = "f2",
	decreaseTimeRate = "f5",
	increaseTimeRate = "f6",
	exportToOsu = { mod = { "ctrl", "shift", "o" } },

	-- Modals
	showKeybinds = { mod = { "ctrl", "k" } },
	showChartInfo = { mod = { "ctrl", "c" } },
	showSkins = { mod = { "ctrl", "s" } },
	showFilters = { mod = { "ctrl", "f" } },
	showInputs = { mod = { "ctrl", "i" } },
	showMultiplayer = { mod = { "ctrl", "m" } },
	showSettings = { mod = { "ctrl", "o" } },
	autoPlay = { mod = { "ctrl", "return" } },
	openEditor = { mod = { "ctrl", "e" } },
	openResult = { mod = { "ctrl", "r" } },

	undoRandom = { mod = { "ctrl", "f2" } },
	deleteLine = { mod = { "ctrl", "backspace" } },
	moveScreenLeft = { mod = { "ctrl", "left" } },
	moveScreenRight = { mod = { "ctrl", "right" } },
	pauseMusic = { mod = { "ctrl", "p" } },
	watchReplay = "w",
	retry = "r",
	submitScore = "s",

	-- Movement
	up = "up",
	down = "down",
	left = "left",
	right = "right",
	up10 = "pageup",
	down10 = "pagedown",
	toStart = "home",
	toEnd = "end",
}
