return {
	global = {
		insertMode = "",
		normalMode = "",
		quit = "escape",
		showKeybinds = { mod = { "lctrl", "rctrl" }, "k" },
		showChartInfo = { mod = { "lctrl", "rctrl" }, "c" },
		increaseVolume = { mod = { "lctrl", "rctrl" }, "'" },
		decreaseVolume = { mod = { "lctrl", "rctrl" }, ";" },
	},
	songSelect = {
		play = "return",
		showMods = "f1",
		random = "f2",
		decreaseTimeRate = "f5",
		increaseTimeRate = "f6",
		undoRandom = { mod = { "lctrl", "rctrl" }, "f2" },
		clearSearch = { mod = { "lctrl", "rctrl" }, "backspace" },
		moveScreenLeft = { mod = { "lctrl", "rctrl" }, "left" },
		moveScreenRight = { mod = { "lctrl", "rctrl" }, "right" },
		pauseMusic = { mod = { "lctrl", "rctrl" }, "p" },
		showSkins = { mod = { "lctrl", "rctrl" }, "s" },
		showFilters = { mod = { "lctrl", "rctrl" }, "f" },
		showInputs = { mod = { "lctrl", "rctrl" }, "i" },
		showMultiplayer = { mod = { "lctrl", "rctrl" }, "m" },
		autoPlay = { mod = { "lctrl", "rctrl" }, "return" },
		openEditor = { mod = { "lctrl", "rctrl" }, "e" },
		openResult = { mod = { "lctrl", "rctrl" }, "r" },
	},
	resultScreen = {
		watchReplay = "w",
		retry = "r",
		submitScore = "s",
	},
	largeList = {
		up = "left",
		down = "right",
		up10 = "pageup",
		down10 = "pagedown",
		toStart = "home",
		toEnd = "end",
	},
	smallList = {
		up = "up",
		down = "down",
	},
}
