return {
	global = {
		insertMode = "i",
		normalMode = "escape",
		quit = { mod = { "lshift", "rshift" }, "escape" },
	},
	songSelect = {
		play = "return",
		random = "r",
		decreaseTimeRate = { mod = {}, "[" },
		increaseTimeRate = { mod = {}, "]" },
		undoRandom = { mod = {}, "u" },
		clearSearch = { mod = {}, op = "dd" },
		moveScreenLeft = { mod = { "lctrl", "rctrl" }, "h" },
		moveScreenRight = { mod = { "lctrl", "rctrl" }, "l" },
		pauseMusic = { mod = { "lctrl", "rctrl" }, "p" },
		showMods = { mod = {}, op = "om" },
		showSkins = { mod = {}, op = "os" },
		showFilters = { mod = {}, op = "of" },
		showInputs = { mod = {}, op = "oi" },
		showMultiplayer = { mod = {}, op = "op" },
		showKeybinds = { mod = {}, op = "ok" },
		openEditor = { mod = {}, op = "oe" },
		autoPlay = { mod = { "lctrl", "rctrl" }, "return" },
	},
	resultScreen = {
		watchReplay = "w",
		retry = "r",
		submitScore = "s",
	},
	largeList = {
		up = "k",
		down = "j",
		up10 = { mod = { "lctrl", "rctrl" }, "u" },
		down10 = { mod = { "lctrl", "rctrl" }, "d" },
		toStart = { mod = {}, op = "gg" },
		toEnd = { mod = { "lshift", "rshift" }, "g" },
	},
	smallList = {
		up = { mod = {}, "h" },
		down = { mod = {}, "l" },
	},
}
