return {
	global = {
		insertMode = "i",
		normalMode = "escape",
		quit = { mod = { "lshift", "rshift" }, "escape" },
		showKeybinds = { op = "ok" },
		showChartInfo = { op = "oc" },
		increaseVolume = "'",
		decreaseVolume = ";",
	},
	songSelect = {
		play = "return",
		random = "r",
		decreaseTimeRate = "[",
		increaseTimeRate = "]",
		undoRandom = "u",
		clearSearch = { op = "dd" },
		moveScreenLeft = { mod = { "lctrl", "rctrl" }, "h" },
		moveScreenRight = { mod = { "lctrl", "rctrl" }, "l" },
		pauseMusic = { mod = { "lctrl", "rctrl" }, "p" },
		showMods = { op = "om" },
		showSkins = { op = "os" },
		showFilters = { op = "of" },
		showInputs = { op = "oi" },
		showMultiplayer = { op = "op" },
		openEditor = { op = "oe" },
		autoPlay = { mod = { "lctrl", "rctrl" }, "return" },
	},
	resultScreen = {
		watchReplay = "w",
		retry = "r",
		submitScore = "s",
	},
	largeList = {
		up = "k",
		down = "j",
		up10 = { mod = { "lctrl", "rctrl" }, "u" },
		down10 = { mod = { "lctrl", "rctrl" }, "d" },
		toStart = { op = "gg" },
		toEnd = { mod = { "lshift", "rshift" }, "g" },
	},
	smallList = {
		up = "h",
		down = "l",
	},
}
