require("thetan.skibidi.patches.Persistence")
require("thetan.skibidi.patches.CacheModel")
require("thetan.skibidi.patches.UserInterface")
require("thetan.skibidi.patches.GameController")
require("thetan.skibidi.patches.GameplayController")
require("thetan.skibidi.patches.RhythmModel")
require("thetan.skibidi.patches.SelectModel")
require("thetan.skibidi.patches.SelectController")
